### PR TITLE
Fixed issue with lazy-import hrefs being adjusted during inlining.

### LINKED ISSUE #504: Lazy Imports not getting resolved correctly in bundles
**Steps to Reproduce:**

1. Clone https://github.com/jay8t6/lazy-import-bundle
2. Run `npm i;bower i`
3. Run `npm run build`
4. Run `polymer serve build/ -o`
5. Open console

**Expected Result:** `paper-button` will lazily import into the side bar

**Actual Result:** `paper-button` doesn't import. You can see in the console that the import failed and resolved to `bower_components/bower_components/paper-button/paper-button.html`

@usergenic

### PR DESCRIPTION
**Pull request by usergenic**
- Lazy import hrefs should not be adjusted, *when* they are governed by assetpath of a containing dom-module.
- Fixes #504 
- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by garlicnation** [comment]
Very cool!

**Comment by stramel** [comment]
A wild @garlicnation appears 😄 

Great work @usergenic 👍

File: src/matchers.ts [hunk 1]
```diff
@@ -95,6 +89,13 @@ export const hiddenDiv: Matcher = predicates.AND(
     predicates.hasAttr('by-polymer-bundler'));
 export const inHiddenDiv: Matcher = predicates.parentMatches(hiddenDiv);
 
+export const elementsWithUrlAttrsToRewrite: Matcher = predicates.AND(
+    predicates.OR.apply(
```
Comment (rictic) [inline src/matchers.ts]: prefer ES6 spread over `apply`:

```javascript
predicates.OR(...constants.URL_ATTR.map(/*...*/))
```

Comment (usergenic) [inline src/matchers.ts]: Totes agreed.  Done.
