### PR TITLE
Going all in on polymer analyzer

### LINKED ISSUE #436: External scripts are stripped out when bundling
When using `google-chart` element with the `polymer-build` 0.8.1 and `polymer-bundler` 2.0.0-pre.6, [this line](https://github.com/GoogleWebComponents/google-chart/blob/master/charts-loader.html#L4) is stripped out of the bundle, which results in the following error:
```
Uncaught ReferenceError: google is not defined
    at HTMLElement.<anonymous> (sandbox-demo-first-sub-page.js:1)
    at i.complete (sandbox-app.js:2)
    at boundComplete (sandbox-app.js:2)
```

I updated my [sandbox](https://github.com/web-padawan/polymer-sandbox) to reproduce this issue, see it live [here](https://sandbox-e0d4b.firebaseapp.com/demo/first/) and open console to see that error.

AFAIK there used to be a `NoopResolver` for such scripts when using `vulcanize` and `hydrolysis`. Looks like this logic is broken for some reasons.

### PR DESCRIPTION
**Pull request by usergenic**
- Uses `polymer-analyzer` directly to obtain import document sources and
   ASTs.  This enforces agreement with the Analyzer as to which documents
   should be inlined/bundled.  (Fixes #436)
 - Fixes issue where protocol-less URLs (those that start with `//`) were
   treated as absolute paths.
 - Renamed/refactored to draw a clearer distinction between ASTs and
   documents.
 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by usergenic** [comment]
A lot of code simply renames `document` to `ast` in places that I'm dealing with `ASTNode` instead of `Document` objects as a way to draw a clear distinction and not use the terms interchangeably.  This is because the rest of the changes involve passing `Document` objects into the import utility functions so they can use `getByKind` to ask for imported document contents or ASTs.

File: src/import-utils.ts [hunk 1]
```diff
@@ -73,97 +73,88 @@ export async function inlineHtmlImport(
...
-  try {
-    script = await loader(resolvedUrl);
-  } catch (e) {
-    // If a script doesn't load, skip inlining.
-    // TODO(usergenic): Add plylog logging for load error.
-    console.warn(`Unable to load script at ${resolvedUrl}: ${e.message}`);
-  }
-
-  if (script === undefined) {
+export async function inlineScript(document: Document, scriptTag: ASTNode) {
```
Comment (justinfagnani) [inline src/import-utils.ts]: This seems like it'll work as long as the document already had the imported URL in its transitive imports. Otherwise, getByKind won't return anything. You might need to pass in a collection of documents?

I'd make sure you have a test for this scenario.

File: src/import-utils.ts [hunk 2]
```diff
@@ -73,97 +73,88 @@ export async function inlineHtmlImport(
...
+  const rawImportUrl = dom5.getAttribute(scriptTag, 'src')!;
+  const resolvedImportUrl = urlLib.resolve(document.url, rawImportUrl);
+  const scriptImport = findInSet(
+      document.getByKind('html-script', {imported: true}),
```
Comment (justinfagnani) [inline src/import-utils.ts]: You need `externalPackages: true` also. Add test.

File: src/ast-utils.ts [hunk 3]
```diff
@@ -13,11 +13,19 @@
...
+import {ASTNode, parse, serialize} from 'parse5';
 
 import * as matchers from './matchers';
 
 /**
+ * Creates a clone of the AST.  The clone is hygenic, by reparsing the
+ * serialized form of the given AST.
+ */
+export function cloneTree(ast: ASTNode): ASTNode {
+  return parse(serialize(ast));
```
Comment (usergenic) [inline src/ast-utils.ts]: Switched to `clone` and removed `cloneTree` function.

File: src/import-utils.ts (hunk 1 above)
Comment (usergenic) [inline src/import-utils.ts]: Added tests to show that bundles which include files not present in the source document successfully have those files inlined and that scripts and css linked to from within html imports added to bundles by the strategy are also inlined.

File: src/import-utils.ts (hunk 2 above)
Comment (usergenic) [inline src/import-utils.ts]: Added a `'html imports from bower_components are inlined'` test

**Comment by usergenic** [comment]
@justinfagnani addressed feedback PTAL

**Comment by usergenic** [comment]
(Note: this PR is not dependent on the new `Analyzer#_fork` method-- that will be in the build PR)

**Comment by web-padawan** [comment]
@usergenic should this fix #436? Please see [my comment](https://github.com/Polymer/polymer-bundler/issues/436#issuecomment-282975732) about external scripts, those are still stripped out with latest `polymer-build` 0.8.2

**Comment by usergenic** [comment]
@web-padawan yes this whole refactor came about as a result of addressing the underlying reasons why #436 was happening.  Thanks for the great bug reports btw!
